# -*- coding: utf-8 -*-
"""quiz.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6CfIPhdbFKVE5_4LQ7I7HLwAlNLuIb3
"""

questions=[
    {
        "Q":"Which deity is revered as the Anemo Archon and protector of Mondstadt?\n 1. Morax 2. Barbatos 3. Baal 4. Buer",
        "A":2
    },

    {

        "Q":"What is Amber's official position and rank within the Knights of Favonius?\n 1. Acting Grand Master 2. Cavalry Captain 3. Outrider 4. Spindrift Knight",
        "A":3
    },

    {
        "Q":"Triggering the Overloaded elemental reaction requires combining which two elements?\n 1. Electro and Pyro 2. Hydro and Cryo 3. Anemo and Geo 4. Dendro and Electro",
        "A":1
    },

    {
        "Q":"The Vigilant Yaksha, Xiao, is famously known to love which specific dish?\n 1. Universal Peace 2. Adeptus' Temptation 3. Grilled Tiger Fish 4. Almond Tofu",
        "A":4
    },

    {
        "Q":"Who famously defeated Kaedehara Kazuha's close friend in the formal duel before the Throne?\n 1. Kamisato Ayato 2. Kujo Sara 3. Sangonomiya Kokomi 4. Arataki Itto",
        "A":2
    }
]
score=0
for i in questions:
  n=int(input(i["Q"]))
  if(n==i["A"]):
    score+=1
  else:
    score=score+0
print("Your score is:",score)