# -*- coding: utf-8 -*-
"""rps.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6CfIPhdbFKVE5_4LQ7I7HLwAlNLuIb3
"""

import random

score = 0

while True:

    n = random.randint(1, 3)

    print("\n1. Rock  2. Paper  3. Scissor")
    p = int(input("Enter your choice: "))

    if p == n:
        print("Draw!")

    elif (p == 1 and n == 3) or (p == 2 and n == 1) or (p == 3 and n == 2):
        print("You won!")
        score += 1

    elif (p == 1 and n == 2) or (p == 2 and n == 3) or (p == 3 and n == 1):
        print("LOSER! :p")

    else:
        print("Invalid choice!")

    s = input("Play again? (yes/no): ").lower()

    if s == "no":
        c = input("Check your score? (yes/no): ").lower()

        if c == "yes":
            print("Your score is:", score)

        break

